# Extract current production definitions for the dependency-isolated state test.
foreach(required SOURCE_DIR OUTPUT_DIR)
    if (NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
function(extract source signature output)
    file(READ "${source}" content)
    string(FIND "${content}" "${signature}\n{\n" start)
    if (start LESS 0)
        message(FATAL_ERROR "Missing function: ${signature}")
    endif()
    string(SUBSTRING "${content}" ${start} -1 tail)
    string(FIND "${tail}" "\n}" end)
    if (end LESS 0)
        message(FATAL_ERROR "Missing end of function: ${signature}")
    endif()
    math(EXPR end "${end} + 2")
    string(SUBSTRING "${tail}" 0 ${end} result)
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
set(new "void GLRenderer3D::SetupPolygonTexture(const RendererPolygon* poly, PolygonTextureState& state) const")
file(READ "${SOURCE_DIR}/src/GPU3D_OpenGL.h" header)
string(FIND "${header}" "    struct PolygonTextureState\n" stateStart)
if (stateStart LESS 0)
    message(FATAL_ERROR "Missing PolygonTextureState definition")
else()
    string(SUBSTRING "${header}" ${stateStart} -1 tail)
    string(FIND "${tail}" "    };" end)
    math(EXPR end "${end} + 6")
    string(SUBSTRING "${tail}" 0 ${end} state)
    extract("${SOURCE_DIR}/src/GPU3D_OpenGL.cpp" "${new}" candidate)
endif()
file(WRITE "${OUTPUT_DIR}/texture-state.inc" "${state}\n")
file(WRITE "${OUTPUT_DIR}/texture-setup.inc" "${candidate}\n")
foreach(method RenderSinglePolygon RenderPolygonBatch RenderPolygonEdgeBatch)
    set(signature "int GLRenderer3D::${method}(int i")
    file(READ "${SOURCE_DIR}/src/GPU3D_OpenGL.cpp" cpp)
    string(FIND "${cpp}" "${signature}, PolygonTextureState& state) const" found)
    if (found LESS 0)
        message(FATAL_ERROR "Missing state-aware caller: ${method}")
    else()
        extract("${SOURCE_DIR}/src/GPU3D_OpenGL.cpp" "${signature}, PolygonTextureState& state) const" body)
    endif()
    file(APPEND "${OUTPUT_DIR}/texture-setup.inc" "${body}\n")
endforeach()
extract("${SOURCE_DIR}/src/GPU3D_OpenGL.cpp" "void GLRenderer3D::SnapshotBlendDestination(int first, int count) const" snapshot)
file(APPEND "${OUTPUT_DIR}/texture-setup.inc" "${snapshot}\n")
