// SPDX-License-Identifier: GPL-3.0-or-later
#include <cstdarg>
#include <cstdio>
#include <cstring>
#include <memory>
#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QSaveFile>
#include <QTemporaryDir>
#ifdef _WIN32
#include <windows.h>
#endif
#include "Platform.h"
#include "Savestate.h"

using namespace melonDS;

enum class WriteFailure { None, ShortWrite, Error };
static WriteFailure writeFailure = WriteFailure::None;

// Inject only the write boundary. Successful/prefix writes use real Qt files.
static qint64 WriteBytes(QIODevice& file, const char* bytes, qint64 length)
{
    if (writeFailure == WriteFailure::Error) return -1;
    if (writeFailure == WriteFailure::ShortWrite) length /= 2;
    return file.write(bytes, length);
}

// Match the legacy frontend's QFile write/count/error conversion for the red run.
namespace melonDS::Platform
{
FileHandle* OpenFile(const std::string& path, FileMode)
{
    auto file = std::make_unique<QFile>(QString::fromStdString(path));
    if (!file->open(QIODevice::WriteOnly | QIODevice::Truncate)) return nullptr;
    return reinterpret_cast<FileHandle*>(file.release());
}

bool CloseFile(FileHandle* file)
{
    auto qfile = reinterpret_cast<QFile*>(file);
    qfile->close();
    delete qfile;
    return true;
}

u64 FileWrite(const void* bytes, u64 size, u64 count, FileHandle* file)
{
    qint64 written = WriteBytes(*reinterpret_cast<QFile*>(file), static_cast<const char*>(bytes), size * count);
    if (written > 0) written /= static_cast<qint64>(size);
    return written;
}

void Log(LogLevel, const char* format, ...)
{
    va_list args;
    va_start(args, format);
    std::vfprintf(stderr, format, args);
    va_end(args);
}
}

class TestSaveFile : public QSaveFile
{
public:
    using QSaveFile::QSaveFile;
    qint64 write(const char* bytes, qint64 length)
    {
        return WriteBytes(*this, bytes, length);
    }
    bool commit()
    {
        const bool result = QSaveFile::commit();
        std::fprintf(stderr, "QSaveFile commit: %s\n", result ? "success" : "failure");
        return result;
    }
};

struct FixtureConsole
{
    enum class Failure { None, ErrorFlag, Reject };
    Failure failure = Failure::None;

    bool DoSavestate(Savestate* state)
    {
        if (failure == Failure::Reject) return false;
        state->Section("TEST");
        if (failure == Failure::ErrorFlag)
        {
            state->VarArray(nullptr, 1); // Exercise the real serializer's error flag.
            return true;
        }
        u32 payload = 0x10203040;
        state->Var32(&payload);
        state->Finish();
        return true;
    }
};

struct StateWriter
{
    FixtureConsole* nds;
    bool saveState(const std::string& filename);
};

// Generated by the existing ExtractFunction.py from the current EmuInstance.cpp.
// No production hooks or copied save algorithm are needed for failure injection.
#define EmuInstance StateWriter
#define QSaveFile TestSaveFile
#include "saveState.inc"
#undef QSaveFile
#undef EmuInstance

static QByteArray Read(const QString& path)
{
    QFile file(path);
    return file.open(QIODevice::ReadOnly) ? file.readAll() : QByteArray();
}

int main(int argc, char** argv)
{
    QCoreApplication app(argc, argv);
    if (argc != 2) return 2;
    QTemporaryDir directory(QDir::current().filePath("savestate-file-io-XXXXXX"));
    if (!directory.isValid()) return 2;
    const QString path = directory.filePath(QStringLiteral("state-\uD55C\uAE00.mln"));

    // The previous file is also a valid generated savestate, with a longer payload.
    Savestate previousState(256);
    QByteArray previousPayload(128, '\xA5');
    previousState.Section("OLD0");
    previousState.VarArray(previousPayload.data(), static_cast<u32>(previousPayload.size()));
    previousState.Finish();
    if (previousState.Error) return 2;
    const QByteArray previous(static_cast<const char*>(previousState.Buffer()), previousState.Length());
    {
        QFile file(path);
        if (!file.open(QIODevice::WriteOnly) || file.write(previous) != previous.size() || !file.flush())
            return 2;
    }

    FixtureConsole console;
    StateWriter writer{&console};
    const bool success = !std::strcmp(argv[1], "roundtrip");
    const bool locked = !std::strcmp(argv[1], "commit-failure");
    if (!std::strcmp(argv[1], "serialize-error")) console.failure = FixtureConsole::Failure::ErrorFlag;
    else if (!std::strcmp(argv[1], "serialize-reject")) console.failure = FixtureConsole::Failure::Reject;
    else if (!std::strcmp(argv[1], "short-write")) writeFailure = WriteFailure::ShortWrite;
    else if (!std::strcmp(argv[1], "write-error")) writeFailure = WriteFailure::Error;
    else if (!success && !locked) return 2;

#ifdef _WIN32
    HANDLE lock = INVALID_HANDLE_VALUE;
    if (locked)
    {
        lock = CreateFileW(reinterpret_cast<LPCWSTR>(path.utf16()), GENERIC_READ,
                           FILE_SHARE_READ, nullptr, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, nullptr);
        if (lock == INVALID_HANDLE_VALUE) return 2;
    }
#else
    if (locked) return 77;
#endif

    const bool saved = writer.saveState(path.toStdString());
#ifdef _WIN32
    if (lock != INVALID_HANDLE_VALUE) CloseHandle(lock);
#endif
    QByteArray actual = Read(path);
    int failures = 0;
    const auto check = [&](bool ok, const char* message) {
        if (!ok) { ++failures; std::fprintf(stderr, "%s\n", message); }
    };
    check(saved == success, "Save result does not report the serialization or I/O failure");
    if (success)
    {
        Savestate loaded(actual.data(), static_cast<u32>(actual.size()), false);
        u32 payload = 0;
        loaded.Section("TEST");
        loaded.Var32(&payload);
        check(!loaded.Error && payload == 0x10203040, "Saved file did not roundtrip through the real serializer");
    }
    else
        check(actual == previous, "Failed save destroyed the previous savestate");

    std::printf("%s: %s (returned=%d, before=%lld bytes, after=%lld bytes)\n",
                argv[1], failures ? "FAIL" : "PASS", saved,
                static_cast<long long>(previous.size()), static_cast<long long>(actual.size()));
    return failures ? 1 : 0;
}
