# Emit aligned integer words, independent of host endianness and runtime paths.
file(WRITE "${OUTPUT_FILE}" "// Generated from the shared compute shaders.\n#include \"EmbeddedShaders.h\"\n#include <stdexcept>\nnamespace melonDS::Vulkan {\nnamespace {\n")
foreach(scale RANGE 1 3)
    foreach(variant RANGE 0 31)
        file(READ "${SHADER_DIR}/${scale}/${variant}.spv" contents HEX)
        string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1," contents "${contents}")
        file(APPEND "${OUTPUT_FILE}" "const uint32_t Shader${scale}_${variant}[] = {${contents}};\n")
    endforeach()
endforeach()
file(APPEND "${OUTPUT_FILE}" "}\nconst ComputePipeline::Shaders& EmbeddedShaders(int scale) {\nswitch (scale) {\n")
foreach(scale RANGE 1 3)
    file(APPEND "${OUTPUT_FILE}" "case ${scale}: {\nstatic const ComputePipeline::Shaders shaders{{\n")
    foreach(variant RANGE 0 31)
        file(APPEND "${OUTPUT_FILE}" "Shader${scale}_${variant},\n")
    endforeach()
    file(APPEND "${OUTPUT_FILE}" "}};\nreturn shaders;\n}\n")
endforeach()
file(APPEND "${OUTPUT_FILE}" "default: throw std::invalid_argument(\"Vulkan scale must be 1, 2 or 3\");\n}\n}\n}\n")
